"""Typed provider contracts used by the pluggable AI layer."""

from app.ai.contracts.assistant import AssistantAnswerProvider, LLMAnswer
from app.ai.contracts.metadata import AITraceMetadata
from app.ai.contracts.explanation import (
    ExplanationBlocker,
    ExplanationClimateMetadata,
    ExplanationEconomicMetadata,
    ExplanationInput,
    ExplanationOutput,
    ExplanationOutputAdapter,
    ExplanationProvider,
    ExplanationPenalty,
    ExplanationRankingSummary,
    ExplanationRiskMetadata,
    ExplanationScoreComponent,
    ExplanationYieldMetadata,
    RankedExplanationRequest,
    SuitabilityExplanationRequest,
    adapt_explanation_output,
    build_explanation_input_from_ranked_request,
    build_explanation_input_from_suitability_request,
)
from app.ai.contracts.extraction import (
    ExtractionInput,
    ExtractionOutput,
    ExtractionProvider,
    ExtractionRequest,
    ExtractionResult,
    TextExtractionProvider,
    build_extraction_input_from_payload,
)
from app.ai.contracts.ranking import RankingAugmentationProvider
from app.ai.contracts.risk import (
    RiskAssessment,
    RiskAssessmentInput,
    RiskScorer,
    RiskScoringProvider,
    RiskScoringRequest,
)
from app.ai.contracts.suitability import SuitabilityProvider
from app.ai.contracts.yield_prediction import (
    YieldClimateSummary,
    YieldCropSummary,
    YieldFieldSummary,
    YieldPredictionInput,
    YieldPredictionOutput,
    YieldPredictionContext,
    YieldPredictionProvider,
    YieldPredictionRequest,
    YieldPredictionServiceClient,
    YieldPredictor,
    YieldSoilSummary,
    adapt_yield_prediction_output,
    build_yield_prediction_input_from_context,
    build_yield_prediction_input_from_entities,
    load_yield_prediction_input,
)

__all__ = [
    "AssistantAnswerProvider",
    "AITraceMetadata",
    "ExplanationBlocker",
    "ExplanationClimateMetadata",
    "ExplanationEconomicMetadata",
    "ExplanationInput",
    "ExplanationOutput",
    "ExplanationOutputAdapter",
    "ExplanationProvider",
    "ExplanationPenalty",
    "ExplanationRankingSummary",
    "ExplanationRiskMetadata",
    "ExplanationScoreComponent",
    "ExplanationYieldMetadata",
    "ExtractionInput",
    "ExtractionOutput",
    "ExtractionProvider",
    "ExtractionRequest",
    "ExtractionResult",
    "LLMAnswer",
    "RankedExplanationRequest",
    "RankingAugmentationProvider",
    "RiskAssessment",
    "RiskAssessmentInput",
    "RiskScorer",
    "RiskScoringProvider",
    "RiskScoringRequest",
    "SuitabilityExplanationRequest",
    "SuitabilityProvider",
    "TextExtractionProvider",
    "adapt_explanation_output",
    "build_extraction_input_from_payload",
    "build_explanation_input_from_ranked_request",
    "build_explanation_input_from_suitability_request",
    "YieldClimateSummary",
    "YieldCropSummary",
    "YieldFieldSummary",
    "YieldPredictionInput",
    "YieldPredictionOutput",
    "YieldPredictionContext",
    "YieldPredictionProvider",
    "YieldPredictionRequest",
    "YieldPredictionServiceClient",
    "YieldPredictor",
    "YieldSoilSummary",
    "adapt_yield_prediction_output",
    "build_yield_prediction_input_from_context",
    "build_yield_prediction_input_from_entities",
    "load_yield_prediction_input",
]
